### ISSUE TITLE
Possibility to send I2C read/write commands to a specific device from the UI?

### ISSUE THREAD

**Issue by snorkman88** [electronicayciencia/EasyMCP2221-GUI#1]
Hola, buenas tardes.
First of all, I wanted to thank you for sharing this tool. 
The UI, together with the CLI examples shown [here](https://github.com/electronicayciencia/EasyMCP2221/blob/master/examples/i2cli.py) and [here](https://github.com/electronicayciencia/EasyMCP2221/blob/master/examples/I2C_Slave_example.py), make the process of interfacing with new sensors for the first time faster and easier than a setup with a conventional MCU and debugger probe.

Would it be possible to add something like this to pre-configure one or more read/write  commands?

<img width="1270" alt="Screenshot 2024-04-28 at 23 09 58" src="https://github.com/electronicayciencia/EasyMCP2221-GUI/assets/31409391/b574ea05-7a92-4c19-b7ef-c61a398aace2">

**Comment by electronicayciencia** [comment]
Hola.
This feature is not planned in a future release of the tool. 

However, you can use [EasyMCP2221's i2cli example](https://github.com/electronicayciencia/EasyMCP2221/blob/master/examples/i2cli.py) as a text-mode I2C interactive terminal.

```console
>python i2cli.py
I2C command line

Enter address from 0x00 to 0x80. S to scan, q to quit > S
Searching...
I2C slave found at address 0x50

Enter address from 0x00 to 0x80. S to scan, q to quit > 0x50

[50] (h for help) > h
h: help
a: set new address
r NN: read NN bytes (default is read one byte)
w xx xx xx ... : write bytes in hex
wr xx xx xx ... : write bytes in hex, no stop signal
q: quit

[50] (h for help) >
```

**Comment by electronicayciencia** [comment]
Hola.
This feature is not planned in a future release of the tool. 

However, you can use [EasyMCP2221's i2cli example](https://github.com/electronicayciencia/EasyMCP2221/blob/master/examples/i2cli.py) as a text-mode I2C interactive terminal.

```console
>python i2cli.py
I2C command line

Enter address from 0x00 to 0x80. S to scan, q to quit > S
Searching...
I2C slave found at address 0x50

Enter address from 0x00 to 0x80. S to scan, q to quit > 0x50

[50] (h for help) > h
h: help
a: set new address
r NN: read NN bytes (default is read one byte)
w xx xx xx ... : write bytes in hex
wr xx xx xx ... : write bytes in hex, no stop signal
q: quit

[50] (h for help) >
```

**Comment by electronicayciencia** [comment]
To configure a device with a predefined set of commands, you can automatize it with i2cli script.

Example. This writes 31 32 33 34 35 to an eeprom and reads it back.

Create a file, named `auto.i2c`:
```console
$ cat auto.i2c
0x50
w 00 00 31 32 33 34 35
wr 00 00
r 5
q
```

Then use this file as an input for i2cli:

```console
$ python i2cli.py < auto.i2c
I2C command line

Enter address from 0x00 to 0x80. S to scan, q to quit >
[50] (h for help) >
[50] (h for help) >
*[50] (h for help) > 31 32 33 34 35   <--- this is the expected output

[50] (h for help) >
```
